image: nixos/unstable
sources:
  - https://git.sr.ht/~pamplemousse/xaviermaso.com
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
secrets:
  - ffce471b-c586-4d54-a9cc-bc729b3bff11
tasks:
  - install: |
      cd xaviermaso.com
      nix develop --command bash -c \
        "npm install"

  - check: |
      cd xaviermaso.com
      nix develop --command bash -c \
        "npm run check"

  - prepare: |
      mkdir -p ~/.config/containers

      cat <<__EOF__ > ~/.config/containers/policy.json
      {
        "default": [{
          "type":"insecureAcceptAnything"
        }]
      }
      __EOF__

  - build: |
      cd xaviermaso.com
      nix develop --command bash -c \
        "npm run build && \
         podman image build . -t docker.io/pamplemousse/xaviermaso.com:latest"

  - push: |
      cd xaviermaso.com
      set +x
      nix develop --command bash -c \
        'podman login docker.io --username pamplemousse --password "$(cat ~/.dockerhub_password)"'
      set -x

      image="docker.io/pamplemousse/xaviermaso.com"
      nix develop --command bash -c \
        "podman push ${image}:latest"

      head="$(git rev-parse HEAD)"
      matching_refs="$(git show-ref | grep "$head" | grep "refs/tags/")" || true
      if [[ "$matching_refs" != "" ]]; then
        tag="$(echo $matching_refs | cut -d'/' -f3)"
        nix develop --command bash -c \
          "podman push ${image}:${tag}"
      fi
triggers:
  - action: email
    condition: failure
    to: admin@xaviermaso.com
