---
language: node_js
node_js: "10"

cache: yarn

services: docker

before_install:
    - npm install -g standard elm@0.18 elm-format

script:
    - npm run check
    - npm run build

after_success:
    - export REPO=pamplemousse/xaviermaso.com
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker build -t $REPO .;
        docker push $REPO;
      fi
    - if [ -n "$TRAVIS_TAG" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker build -t $REPO:$TRAVIS_TAG .;
        docker push $REPO:$TRAVIS_TAG;
      fi
