name: "Build"
on:
  push:
    branches:
    - master
    tags:
    - '*'
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - uses: docker/setup-buildx-action@v1

    - name: Install JS dependencies
      run: npm install

    - name: Check
      run: npm run check

    - name: Build the application
      run: npm run build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push latest Docker image
      if: github.ref_name == 'master'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/xaviermaso.com:latest

    - name: Build and push tagged Docker image
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/xaviermaso.com:${{ github.ref_name }}
